/**
 * Writes `src/environments/environment.autogen.ts` from `NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY`
 * in the environment or in `frontend/.env` so `ng serve` / `ng build` pick up the publishable key.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const envPath = path.join(root, '.env');

let key = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY?.trim() ?? '';

if (!key && fs.existsSync(envPath)) {
  const content = fs.readFileSync(envPath, 'utf8');
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    if (trimmed.startsWith('NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=')) {
      key = trimmed.slice('NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY='.length).trim();
      break;
    }
  }
}

const outPath = path.join(root, 'src', 'environments', 'environment.autogen.ts');
const body = `/* eslint-disable */
// Auto-generated by scripts/clerk-env.mjs — do not edit by hand
export const clerkPublishableKey = ${JSON.stringify(key)};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, body, 'utf8');
process.stderr.write(`clerk-env: wrote ${path.relative(root, outPath)} (${key ? 'key set' : 'empty'})\n`);
